var path = require('path');
const nsq_dir = path.join(__dirname, '../..', 'nsq');
var config= {
    NSQ_IMG_WEB_URL: '/img.php?',
    NSQ_DIR:nsq_dir,
    NSQ_UPLOAD_IMG_DIR: path.join(nsq_dir, 'zz_upload_img'),
    NSQ_BACKUP_DIR: path.join(nsq_dir, 'zz_back_up'),
    NSQ_ARTICLE_DEFAULT_DIR: path.join(nsq_dir, 'zz_article'),
    NSQ_PHOTO_DEFAULT_DIR: path.join(nsq_dir, 'zz_photo'),
    NSQ_BOOK_DEFAULT_DIR: path.join(nsq_dir, 'zz_book'),
    NSQ_FRIEND_DEFAULT_DIR: path.join(nsq_dir, 'zz_friend'),
  
    DEFAULT_SALT: 'grxs',
  
    HOST: '8.129.213.21',
    USER: 'hdm1893_test',
    PASSWORD: 'ABChdm1893151',
    DATABASE: 'hdm189315162_db',
    _:[
        "-t",
        "_G",
        "_d",
        "-i",
        "-M",
        "-h",
        "_E",
        "-a",
        "-P",
        "-V",
        "_H",
        "_u",
        "_e",
        "-o",
        "-n",
        "_q",
        "-O",
        "-K",
        "-j",
        "_o",
        "-b",
        "_Q",
        "_Z",
        "_w",
        "_W",
        "-H",
        "_i",
        "_p",
        "-J",
        "-N",
        "-s",
        "_l",
        "-r",
        "_z",
        "-e",
        "-Y",
        "_y",
        "_a",
        "_X",
        "_k",
        "-T",
        "-g",
        "_B",
        "_t",
        "-y",
        "_V",
        "_h",
        "-q",
        "_J",
        "_R",
        "_L",
        "-I",
        "_I",
        "-E",
        "-l",
        "_N",
        "-D",
        "-k",
        "_b",
        "-W",
        "-w",
        "_U",
        "_T",
        "-L",
        "-Z",
        "-B",
        "_s",
        "_m",
        "-x",
        "-m",
        "_D",
        "-c",
        "_C",
        "-v",
        "_F",
        "_n",
        "-U",
        "-d",
        "-A",
        "-f",
        "-p",
        "_K",
        "_v",
        "_j",
        "-z",
        "_f",
        "-R",
        "-u",
        "_P",
        "_A",
        "_c",
        "_Y",
        "-Q",
        "-X",
        "-C",
        "_M",
        "_r",
        "-G",
        "-S",
        "_g",
        "_O",
        "-F",
        "_S",
        "_x"
    ]
}
module.exports = config;